routes/web.php
<?php

use App\Http\Controllers\JenisController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\WarnaController;
use App\Models\Produk;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('/');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('/home');

//Start Produk
Route::resource('produk',\App\Http\Controllers\ProdukController::class);

// Route::get('produk-detail/', [\App\Http\Controllers\ProdukDetailController::class, 'index'])->name('produk-detail.index');
// Route::get('/produk-detail/create/{id}', [\App\Http\Controllers\ProdukDetailController::class, 'create'])->name('produk-detail.create');
// });
// Route::post('produk-detail/store', [\App\Http\Controllers\ProdukDetailController::class, 'store'])->name('produk-detail.store');

Route::resource('produk-detail',\App\Http\Controllers\ProdukDetailController::class);

//Start Master
Route::resource('jenis',\App\Http\Controllers\JenisController::class);
Route::resource('warna',\App\Http\Controllers\WarnaController::class);

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
Use App\Models\Jenis;
use App\Models\Detail;

class Produk extends Model
{
    protected $guarded = ['id'];
    protected $table = 'produks';
    protected $primaryKey = 'id';

    public function jenis()
    {
        return $this->belongsTo(Jenis::class);
    }

    public function detail()
    {
        return $this->hasMany(Detail::class,'produk_id','id');
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Produk;
use App\Models\Jenis;
use App\Models\Detail;
use App\Models\Warna;


class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Res
     *
     *ponse
     */
    public function index()
    {
        $data['produk'] = Produk::with(['jenis', 'detail'])->get();
        return view('admin.produk.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function data()
    // {
    //     $datas = Produk::with(['jenis', 'detail'])->get();
    //     // dd($datas);
    //     return view('data', compact('datas'));
    // }
    public function create()
    {
        $data['jenis'] = Jenis::all();
        return view('admin.produk.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'nama' => 'required',
            'hpp' => 'required',
            'harga_jual' => 'required',
        ];

        $customMessages = [
            'nama.required' => 'Produk wajib diisi!',
            'hpp.required' => 'HPP wajib diisi!',
            'harga_jual.required' => 'Harga wajib diisi!',
        ];

        $this->validate($request, $rules, $customMessages);

        //Start Input
        $input = $request->all();
        $status = Produk::create($input);

        if ($status){
            return redirect()->route('produk.index')->with('success', 'Data Produk berhasil ditambahkan');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['produk'] = Produk::find($id);
        $data['jenis'] = Jenis::all();
        return view('admin.produk.detail', $data);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['jenis'] = Jenis::all();
        $data['produk']= Produk::find($id);
        $data['warna'] = Warna::all();
        $data['detail'] = Detail::all();

        return view('admin.produk.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validProduk = $request->validate([
            'nama' => 'required|string',
            'jenis_id' => 'required',
            'hpp' => 'required|numeric',
            'harga_jual' => 'required|numeric',
        ]);

        // $request->validate([
        //     'warna_id' => 'required',
        //     'stok' => 'required|numeric',
            // 'foto_produk' => 'required',
            // 'foto_produk.*' => 'image|mimes:jpeg,png,jpg|max:2048'
        // ]);

        $produk = Produk::find($id);
        // $produkDet = Detail::find($id);


        // if($request->foto_produk){
        //     $imageName = time() . '.' . $request->foto_produk->extension();
        //     $request->foto_produk->move(public_path() . '/image/foto_produk/', $imageName);
        //     $dataUpdate['foto_produk'] = $imageName;
        // }

        // if ($request->foto_produk){
        //     $imageName = time() . '.' . $request->foto_produk->extension();
        //     $request->foto_produk->move(public_path() . '/image/foto_produk/', $imageName);
        // } else {
        //     $imageName = $produkDet->foto_produk;
        // }

        $produk = $produk->update([
            // 'produk_id' => $produk->id,
            // 'detail' => $produkDet->id,
            'nama' => $request['nama'],
            'jenis_id' => $request['jenis_id'],
            // 'warna_id' => $request['warna_id'],
            // 'stok' => $request['stok'],
            'hpp' => $request['hpp'],
            'harga_jual' => $request['harga_jual'],
            // 'foto_produk' => $imageName,
        ]);

        return redirect()->route('produk.index')->with('success', 'Data Produk berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $produk = Produk::find($id);
        $status = $produk->delete();
        if ($status){
            return 1;
        }else{
            return 0;
        }
    }
}

resources/views/admin/produk/detail.blade.php
@extends('admin.layouts.app')
@section('title','Data Produk')
@section('detail','active')

@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Detail Produk</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('produk.index')}}">Index</a>
                                    </li>
                                    <li class="breadcrumb-item active">{{(@$produk ? ' Detail' : ' Detail')}} Produk
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <div class="row" id="basic-table">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <a href="{{route('produk-detail.create')}}" class="btn btn-primary waves-effect waves-float waves-light">Tambah Detail Produk</a>
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Warna</th>
                                        <th>Stok</th>
                                        <th>Deskripsi</th>
                                        <th>Spesifikasi</th>
                                        <th>Foto Produk</th>
                                        <th>Aksi</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($produk as $row)
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                            <td>{{$row->warna->warna}}</td>
                                            <td>{{$row->stok}}</td>
                                            <td>{{$row->deskripsi}}</td>
                                            <td>{{$row->spesifikasi}}</td>
                                            <td><img class="card-img-top" src="{{ asset ('/image/foto_produk/'. $row->foto_produk) }}" alt="Ukulele" style="object-fit: cover; border-radius: 6px; width:120px;"/></td>
                                            <td>
                                                <a href="{{route('produk-detail.edit', $row->id)}}" class="btn btn-warning waves-effect waves-float waves-light">Edit</a>
                                                <a href="#" data-id="{{$row->id}}" class="btn btn-danger btn-del waves-effect waves-float waves-light">Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Basic Tables end ,$produk->id) -->
            </div>
        </div>
    </div>
@endsection

@push('styles')
@endpush

@push('scripts')
    <script>
        $(document).ready(function () {
            $(document).on('click', '.btn-del', function () {
                var id = $(this).data('id');
                Swal.fire({
                    icon: 'error',
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    type: 'error',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                })
                    .then((result) => {
                        if (result.value) {
                            $.ajax({
                                'url': '{{url('produk-detail')}}/' + id,
                                'type': 'post',
                                'data': {
                                    '_method': 'DELETE',
                                    '_token': '{{csrf_token()}}'
                                },
                                success: function (response) {
                                    if (response == 1) {
                                        toastr.success('Data berhasil dihapus!', 'Berhasil!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                        location.reload();
                                    } else {
                                        toastr.error('Data gagal dihapus!', 'Gagal!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                    }
                                }
                            });
                        } else {
                            console.log(`dialog was dismissed by ${result.dismiss}`)
                        }

                    });
            });

        });

    </script>
@endpush

resources/views/admin/produk/form-detail.blade.php
@extends('admin.layouts.app')
@section('detail','active')

@section('title')
    Form {{@$produk ? ' Ubah' : ' Tambah'}}
@endsection
@section('content')
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">Data Produk</h2>
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{route('produk-detail.index')}}">Index</a>
                                    </li>
                                    <li class="breadcrumb-item active">{{(@$produk ? ' Ubah Detail' : ' Tambah Detail')}} Produk
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Basic Tables start -->
                <section id="basic-vertical-layouts">
                    <div class="row">
                        <div class=" col-12">
                            <div class="card">
                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <h4 class="alert-heading">Error!</h4>
                                            <div class="alert-body">
                                                <ul>
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        </div>
                                    @endif
                                    <form class="form form-vertical"  action="{{@$produk ? route('produk-detail.update',$produk->id) : route('produk-detail.store')}}"
                                          method="POST" enctype="multipart/form-data">
                                        @csrf
                                        @if(@$produk)
                                            {{method_field('patch')}}
                                        @endif
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="warna_id">Warna</label>
                                                    <select class="form-select form-control" id="warna_id" name="warna_id" >
                                                        <option value="">- Pilih Warna Produk -</option>
                                                        @foreach($warna as $row)
                                                            <option value="{{$row->id}}" {{@$produk && $produk->warna_id == $row->id ? 'selected' : '' }}>{{$row->warna}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="stok">Stok</label>
                                                    <input type="number" min="0" id="stok" class="form-control" name="stok" placeholder="10"
                                                           value="{{old('stok', @$produk ? $produk->stok : '')}}""/>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="deskripsi">Deskripsi</label>
                                                    <textarea type="text" class="form-control" name="deskripsi" value="">{{old('deskripsi', @$produk ? $produk->deskripsi : '')}}</textarea>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="spesifikasi">Spesifikasi</label>
                                                    <textarea type="text" class="form-control" name="spesifikasi" value="">{{old('spesifikasi', @$produk ? $produk->spesifikasi : '')}}</textarea>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label for="foto_produk">Foto Produk</label>
                                                    <input type="file" id="foto_produk" class="form-control" name="foto_produk" placeholder=""
                                                           value="{{old('foto_produk', @$produk ? $produk->foto_produk : '')}}">
                                                </div>
                                            </div>


                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary mr-1">Submit</button>
                                                <a href="{{route('produk-detail.index')}}" type="reset" class="btn btn-outline-secondary">Cancel</a>
                                            </div>
                                        </div>
                                    </form>


                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Tables end -->
            </div>
        </div>
    </div>

@endsection

@push('styles')
@endpush

@push('scripts')
    <script>

    </script>
@endpush

resources/views/admin/produk/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Data Produk')
@section('ukulele', 'active')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Data Produk</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
{{--                                    <li class="breadcrumb-item"><a href="{{route('jenis.index')}}">jenis</a>--}}
{{--                                    </li>--}}
                                <li class="breadcrumb-item active">Index
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                <div class="form-group breadcrumb-right">
                    <div class="dropdown">
                        <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="app-todo.html"><i class="mr-1" data-feather="check-square"></i><span class="align-middle">Todo</span></a><a class="dropdown-item" href="app-chat.html"><i class="mr-1" data-feather="message-square"></i><span class="align-middle">Chat</span></a><a class="dropdown-item" href="app-email.html"><i class="mr-1" data-feather="mail"></i><span class="align-middle">Email</span></a><a class="dropdown-item" href="app-calendar.html"><i class="mr-1" data-feather="calendar"></i><span class="align-middle">Calendar</span></a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <div class="row" id="basic-table">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{route('produk.create')}}" class="btn btn-primary waves-effect waves-float waves-light">Tambah Produk</a>
                        </div>
                    </div>
                </div>
            </div>
            <section id="card-demo-example">
                <div class="row match-height">
                    @foreach($produk as $row)
                        <div class="col-md-6 col-lg-4">
                            <div class="card">
                                <img class="card-img-top" src="{{asset('assets')}}/admin/images/slider/uke_soprano_full.jpg" alt="Ukulele">
                                <div class="card-body">
                                    <a href="{{route('produk.show',$row->id)}}"><h4 class="card-title">{{$row->nama}}</h4></a>
                                    <p class="card-text">
                                        HPP : Rp. {{$row->hpp}}<br>
                                        Harga Jual: Rp. {{$row->harga_jual}}
                                    </p>
                                    <a href="{{route('produk-detail.index',$row->id)}}" class="btn btn-primary waves-effect waves-float waves-light">View More</a>
                                    <a href="{{route('produk.edit', $row->id)}}" class="btn btn-warning waves-effect waves-float waves-light">Edit</a>
                                    <a href="#" data-id="{{$row->id}}" class="btn btn-danger btn-del waves-effect waves-float waves-light">Delete</a>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
            </section>
        </div>
    </div>
</div>


@endsection

@push('styles')
@endpush

@push('scripts')
    <script>
        $(document).ready(function () {
            $(document).on('click', '.btn-del', function () {
                var id = $(this).data('id');
                Swal.fire({
                    icon: 'error',
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    type: 'error',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                })
                    .then((result) => {
                        if (result.value) {
                            $.ajax({
                                'url': '{{url('produk')}}/' + id,
                                'type': 'post',
                                'data': {
                                    '_method': 'DELETE',
                                    '_token': '{{csrf_token()}}'
                                },
                                success: function (response) {
                                    if (response == 1) {
                                        toastr.success('Data berhasil dihapus!', 'Berhasil!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                        location.reload();
                                    } else {
                                        toastr.error('Data gagal dihapus!', 'Gagal!', {
                                            closeButton: true,
                                            tapToDismiss: false
                                        });
                                    }
                                }
                            });
                        } else {
                            console.log(`dialog was dismissed by ${result.dismiss}`)
                        }

                    });
            });

        });

    </script>
@endpush